# Generated by Django 3.2.8 on 2021-11-28 07:52

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20211126_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.user_documents_path),
        ),
        migrations.AlterField(
            model_name='personal',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('intersex', 'Intersex')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_id_path),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_id_path),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/profile/user_0/profile.png', null=True, upload_to=profiles.models.user_profile_path),
        ),
    ]
