# Generated by Django 3.2.8 on 2021-10-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cancel_reject_done_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
