# Generated by Django 3.2.8 on 2021-10-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_cancel_reject_done_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
