# Generated by Django 3.2.8 on 2021-11-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20211103_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.FileField(blank=True, default='job_images/jobs.jpg', null=True, upload_to='jobs/job_images/'),
        ),
    ]
