# Generated by Django 3.2.8 on 2021-11-10 07:45

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_job_reference'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='NewGinIndex'),
        ),
    ]
