# Generated by Django 3.2.8 on 2021-11-10 07:50

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_newginindex'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='NewGinIndex',
        ),
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='NewGinIndex', opclasses=['gin_trgm_ops']),
        ),
    ]
