# Generated by Django 3.2.8 on 2021-11-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20211110_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='done_at_date',
            new_name='application_deadline',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='done_by_date',
            new_name='job_done_date',
        ),
    ]
