# Generated by Django 3.2.8 on 2021-11-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20211110_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location_address_location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='location_county',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='location_exact_job_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location_town',
        ),
    ]
