# Generated by Django 3.2.8 on 2021-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20211118_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.FileField(blank=True, default='jobs/job_images/jobs.jpg', null=True, upload_to='jobs/job_images/'),
        ),
    ]
