# Generated by Django 3.2.8 on 2021-12-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(blank=True, default='jobs/job_images/jobs.jpg', null=True, upload_to='jobs/job_images/'),
        ),
    ]
