# Generated by Django 3.2.8 on 2022-08-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_jobimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
