# Generated by Django 3.2.8 on 2021-11-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contant',
            new_name='Contact',
        ),
    ]
