# Generated by Django 3.2.8 on 2022-02-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_comment',
            name='likes',
        ),
    ]
